# fly.toml app configuration file generated for downmark
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'downmark'
primary_region = 'sjc'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  http_request_timeout = 120

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 40

[[vm]]
  size = 'shared-cpu-2x'
  memory = '4gb'

[env]
  PORT = '3000'
  HOST = '0.0.0.0'
  NODE_ENV = 'production'
  PANDOC_SERVICE_URL = 'http://downmark-pandoc.internal:3001'
  RP_ID = 'downmark.fly.dev'
  RP_NAME = 'Downmark - Web to Markdown'
  ORIGIN = 'https://downmark.fly.dev'
  AUTH_ENABLED = 'false'
